/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"*/

class Solution {
    public char findTheDifference(String s, String t) {
        // char result = 0;
        // for(int i = 0; i < s.length();i++){
        //     result ^= s.charAt(i);
        // }

        //     for(int i = 0; i < t.length();i++){
        //         result ^= t.charAt(i);
        //     }
            

        
        // return result;

        HashMap<Character,Integer> map = new HashMap<>();

        for(char ch : s.toCharArray()){
            map.put(ch,map.getOrDefault(ch,0)+1);

        }
        for(char c : t.toCharArray()){
            if(!map.containsKey(c) || map.get(c)== 0){
                return c;
            }
        
        map.put(c,map.get(c)-1);
        }
        return ' ';
       





    }
}
